config/routes.rb
PustMedApp::Application.routes.draw do
  root  'static_pages#home'
  match '/about',      to: 'static_pages#about',     via: 'get'
  match '/academics',  to: 'static_pages#academics', via: 'get'
  match '/life',       to: 'static_pages#life',      via: 'get'
  match '/give',       to: 'static_pages#give',      via: 'get'
  match '/contact',    to: 'static_pages#contact',   via: 'get'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def academics
  end

  def life
  end

  def give
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# Returns the full title on a per-page basis
	def full_title(page_title)
		base_title = "PUST Medical Sciences"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
	
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<div id="footer-top-1"></div>
	<div id="footer-top-2"></div>
	<div id="footer-main" class="container">
	  <small>
	    PUST Medical Sciences
	  </small>
	  <nav>
	    <ul>
	      <li><%= link_to "About",   '#' %></li>
	      <li><%= link_to "Contact", '#' %></li>
	    </ul>
	  </nav>
	</div> <!-- /.footer-main -->
	<div id="footer-copyright" class="center">&copy; 2014 PUST Medical Sciences. All rights reserved.</div>
	<div id="footer-base"></div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-fixed-top navbar-inverse" id="navbar-main">
    <div class="container">
      <div class="navbar-header">
        <button type="button" id="collapse-button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
         <span class="sr-only">Toggle navigation</span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
       </button>
       <%= link_to "pust medical sciences", '#', id: "logo", class: 'navbar-brand' %>
       </div> <!-- /.navbar-header -->
       <div class="collapse navbar-collapse">
         <ul class="nav navbar-nav navbar-left">
           <li><%= link_to "HOME",         root_path %></li>
           <li><%= link_to "ABOUT",        about_path %></li>
           <li><%= link_to "ACADEMICS",    academics_path %></li>
           <li><%= link_to "LIFE AT PUMS", life_path %></li>
           <li><%= link_to "GIVE",         give_path %></li>
           <li><%= link_to "CONTACT",      contact_path %></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <div id="carousel-header" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#carousel-header" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-header" data-slide-to="1"></li>
      <li data-target="#carousel-header" data-slide-to="2"></li>
    </ol>
    <!-- ./Indicators -->

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
        <%= image_tag "carousel-main-01.jpg", alt: "Carousel 1" %>
        <div class="carousel-caption carousel-hero-unit">
          <h1>PUST Medical Sciences</h1>
          <p>
            delivers the promise of the highest quality healthcare and 
            medical education to meet the real needs of people of 
            DPRK and East Asia.
          </p>
        </div>
      </div>

      <div class="item">
        <%= image_tag "carousel-main-02.jpg", alt: "Carousel 2" %>
        <div class="carousel-caption">
          <!-- Insert caption here -->
        </div>
      </div>

      <div class="item">
        <%= image_tag "carousel-main-03.jpg", alt: "Carousel 3" %>
        <div class="carousel-caption">
          <!-- Insert caption here -->
        </div>
      </div>
    </div>
    <!-- ./Wrapper for slides -->

    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-header" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="#carousel-header" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
    </a>
    <!-- ./Controls -->

  </div><!-- /.#carousel-header -->
  <div id="header-shadow">
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
		<title><%= full_title(yield(:title)) %></title>
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
		<%= render 'layouts/shim' %>
  </head>
  <body>
  	<%= render 'layouts/header' %>
    <div id="main" class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1><span class="h-bar">&nbsp;</span>&nbsp;Mission Statement</h1>
<p>
	The mission of the PUST Medical Sciences is to create a self-sustaining, innovative, and competitive academic institution which equips students of the DPRK with world class training, high quality faculty and resources that enable them to become physicians, pharmacists, dentists, nurses, and public health officials serving real needs of people of the DPRK and East Asia.
</p>
<p>
	The PUST Medical Sciences consists of the five programs:
</p>
<ul class="lato">
	<li>Medicine</li>
	<li>Pharmacy</li>
	<li>Dentistry</li>
	<li>Nursing</li>
	<li>Public Health</li>
</ul>
<p>
	Training will be drawn from international expertise and research so that students of the PUST Medical Sciences will be acknowledged by international standards in their respective fields.
</p>

<h1><span class="h-bar">&nbsp;</span>&nbsp;Founder's Story</h1>
<p>
	[TBD]
</p>

<h1><span class="h-bar">&nbsp;</span>&nbsp;Message from PK</h1>
<p>
	[TBD]
</p>

<h1><span class="h-bar">&nbsp;</span>&nbsp;Timeline</h1>
<p>
	[TBD]
</p>

app/views/static_pages/academics.html.erb
<% provide(:title, 'Academics') %>

<h1><span class="h-bar">&nbsp;</span>&nbsp;Divisions Overview</h1>
<p>
	[TBD]
</p>

<h1><span class="h-bar">&nbsp;</span>&nbsp;School of Dentistry</h1>
<p>
	[TBD]
</p>

<h1><span class="h-bar">&nbsp;</span>&nbsp;School of Medicine</h1>
<p>
	[TBD]
</p>

<h1><span class="h-bar">&nbsp;</span>&nbsp;School of Pharmacy</h1>
<p>
	[TBD]
</p>

<h1><span class="h-bar">&nbsp;</span>&nbsp;School of Public Health</h1>
<p>
	[TBD]
</p>

<h1><span class="h-bar">&nbsp;</span>&nbsp;School of Nursing</h1>
<p>
	[TBD]
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact PUMS') %>
<h1><span class="h-bar">&nbsp;</span>&nbsp;Contact Us</h1>
<p>
	[Contact info]
</p>


app/views/static_pages/give.html.erb
<% provide(:title, 'Give') %>

<h1><span class="h-bar">&nbsp;</span>&nbsp;Giving to PUST Medical Sciences</h1>
<p>
	[TBD]
</p>

<h1><span class="h-bar">&nbsp;</span>&nbsp;Donate to the YUST PUST Foundation</h1>
<p>
	[TBD]
</p>

<h1><span class="h-bar">&nbsp;</span>&nbsp;Volunteer</h1>
<p>
	[Information about giving time and resources]
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<h1><span class="h-bar">&nbsp;</span>&nbsp;Mission Statement</h1>
<p>
	The mission of the PUST Medical Sciences is to create a self-sustaining, innovative, and competitive academic institution which equips students of the DPRK with world class training, high quality faculty and resources that enable them to become physicians, pharmacists, dentists, nurses, and public health officials serving real needs of people of the DPRK and East Asia.
</p>
<p>
	The PUST Medical Sciences consists of the five programs:
</p>
<ul class="lato">
	<li>Medicine</li>
	<li>Pharmacy</li>
	<li>Dentistry</li>
	<li>Nursing</li>
	<li>Public Health</li>
</ul>
<p>
	Training will be drawn from international expertise and research so that students of the PUST Medical Sciences will be acknowledged by international standards in their respective fields.
</p>

<h1><span class="h-bar">&nbsp;</span>&nbsp;Core Values</h1>
<p>
	We strive to achieve the PUST Medical Sciences' Vision by implementing the following core values:
</p>
<ul class="lato">
	<li>Excellence in pragmatic medical education</li>
	<li>Integrity of leadership, medicine students, and healthcare providers</li>
	<li>Respect and diversity</li>
</ul>
	

app/views/static_pages/life.html.erb
<% provide(:title, 'Life at PUMS') %>

<h1><span class="h-bar">&nbsp;</span>&nbsp;Life at PUST Medical Sciences</h1>
<p>
	[Brief explanation of how students and faculty live and learn together]
</p>

<h1><span class="h-bar">&nbsp;</span>&nbsp;Events</h1>
<p>
	[Potential blog-style]
</p>
<p>
	[Groundbreaking]
</p>
<p>
	[Graduation]
</p>